"""Generates the Domum Ornamentum templates (DO-1): every DO shape converted to a model reading its material layout,
one template block per shape with its states, rotation, hitbox and connections, the shape manifest and the creative
tab; the materials themselves are chosen at runtime (docs/superpowers/specs/2026-09-28-hycolony-domum-ornamentum-
do1-design.md).

Run by hand, then commit the outputs (the DomumOrnamentum pack and plugin/src/main/resources/hycolony/ornament/): the
build never runs it. Downloads DO's pinned commit once into build/domum-cache/. Needs Python 3.10+ and Pillow.

    python tools/domum/generate.py [path/to/release-0.6.8-Assets.zip]
"""

import shutil
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1] / "decorations"))
import manifest  # noqa: E402
import source  # noqa: E402
import tabs  # noqa: E402
import tags  # noqa: E402
import validate  # noqa: E402
from blocks import common, compat, door, pane, pillar, roof, static  # noqa: E402
from families import FAMILIES  # noqa: E402
from pack import ROOT, validate_pack, write_json  # noqa: E402

PACK = ROOT / "plugin" / "src" / "subplugins" / "DomumOrnamentum"
RESOURCES = ROOT / "plugin" / "src" / "main" / "resources"
# Mechanism -> the module writing its templates; mechanisms not listed yet are generated by later DO-1 tasks.
GENERATORS = {"static": static.generate, "roof": roof.shingles, "shingle_slab": roof.shingle_slab,
              "door": door.doors, "trapdoor": door.trapdoors, "pillar": pillar.generate, "pane": pane.generate,
              "vanilla": compat.generate}


def run(pack, resources, assets):
    """Regenerates everything into pack and resources; returns the Context. Fails on an invalid pack."""
    for generated in ("Common", "Server"):
        shutil.rmtree(pack / generated, ignore_errors=True)
    shutil.rmtree(resources / "hycolony" / "ornament", ignore_errors=True)
    ctx = common.Context(assets, source.fetch(), pack, resources, tags.build(assets))
    for family in FAMILIES:
        generator = GENERATORS.get(family.mechanism)
        # All-brick blocks are forge:composite models (material cube + brick overlay) over vanilla geometry: the
        # compat task generates them with the other families built on Minecraft's vanilla models.
        if generator and not family.name.startswith("AllBrick"):
            generator(ctx, family)
    manifest.write(ctx)
    ctx.tab = tabs.generate(ctx)
    write_json(pack / "hycolony" / "id-map.json", {"ornamentTags": ctx.tags})
    for language, lines in ctx.lang.items():
        path = pack / "Server" / "Languages" / language / "hycolony.lang"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(sorted(lines)) + "\n", encoding="utf-8", newline="\n")
    validate_pack(assets, pack)
    validate.pack(ctx)
    return ctx


def main():
    ctx = run(PACK, RESOURCES, tags.open_assets(sys.argv[1] if len(sys.argv) > 1 else None))
    print(f"{len(ctx.items)} templates, {len(ctx.shapes)} shapes")


if __name__ == "__main__":
    main()
